{
  "formatVersion": "1.1",
  "component": {
    "group": "io.synaps",
    "module": "sdk",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sdk-0.0.3.aar",
          "url": "sdk-0.0.3.aar",
          "size": 38740,
          "sha512": "4fc9539b85b566205d0417f4dec320a6ac1c3323c8b72f41438229a2457e730b262dc1f2b2f0979ce538430eb371339967f1a661b622b66a56d632124caf0e8e",
          "sha256": "95df180f0b75f3b6037cc051649e0a04ce60d6ceee7c62d51f67365767a376a3",
          "sha1": "08a37f38e101c9dc2cf11fe233903b9a15113561",
          "md5": "c817954b701b78a280f994e9a5a625a7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.3.aar",
          "url": "sdk-0.0.3.aar",
          "size": 38740,
          "sha512": "4fc9539b85b566205d0417f4dec320a6ac1c3323c8b72f41438229a2457e730b262dc1f2b2f0979ce538430eb371339967f1a661b622b66a56d632124caf0e8e",
          "sha256": "95df180f0b75f3b6037cc051649e0a04ce60d6ceee7c62d51f67365767a376a3",
          "sha1": "08a37f38e101c9dc2cf11fe233903b9a15113561",
          "md5": "c817954b701b78a280f994e9a5a625a7"
        }
      ]
    }
  ]
}
